#!/usr/bin/env python3
"""Regenerates docs/WORKFLOW_PARITY.md from docs/browser_workflows.json and the ported set (crates/ffworks-core/assets/workflows/*.tsv)."""
import json, os, collections, glob
root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
w = json.load(open(os.path.join(root, "docs", "browser_workflows.json")))
ported = set()
for f in glob.glob(os.path.join(root, "crates", "ffworks-core", "assets", "workflows", "*_workflows.tsv")):
    ported |= {l.split("\t")[0] for l in open(f) if l.strip()}
export_ops = {"extract-mp3": "audio-only export (FFWORKS has WAV, FLAC and MP3 export presets; AAC audio export is not a preset)", "extract-wav": "audio-only export: use the WAV preset", "extract-aac": "audio-only export (no AAC audio-only preset yet)", "stereo-to-mono": "its settings only re-encode; no channel change in the catalogue", "sample-rate-48k": "a project/export sample-rate setting, not a clip workflow", "sample-rate-441": "a project/export sample-rate setting, not a clip workflow"}
native = {i: "FFWORKS does this natively: clip speed (Inspector)" for i in ("slow-0_5x", "slow-0_25x", "speed-2x", "speed-4x", "speed-8x")}
native.update({"reverse-video": "FFWORKS does this natively: clip Reverse", "fade-in-out": "FFWORKS does this natively: clip fade in / fade out", "rotate-90-cw": "FFWORKS does this natively: clip transform rotation (90)", "rotate-90-ccw": "FFWORKS does this natively: clip transform rotation (-90)", "rotate-180": "FFWORKS does this natively: clip transform rotation (180)", "mute-strip-audio": "FFWORKS does this natively: mute a track or leave the audio out", "preview-10s": "FFWORKS does this natively: export a range"})
by = collections.OrderedDict()
for x in w: by.setdefault(x["category"], []).append(x)
def kind(x):
    if "fullChain" in x: return "audio filter chain"
    if x.get("pipelineSteps"): return "multi-step pipeline (described, steps built in app code)"
    if x.get("settings"): return "settings of the browser app's control panel"
    if "settings" in x: return "format/codec only"
    return "built in app code"
def status(x):
    if x["id"] in ported: return "**ported**"
    if x["id"] in export_ops: return "not a clip workflow: " + export_ops[x["id"]]
    if x["id"] in native: return native[x["id"]] + " (not a one-click workflow; not compared against the browser app)"
    return "not ported"
n_port = sum(1 for x in w if x["id"] in ported)
L = ["# Browser app workflows → FFWORKS parity\n",
     f"Generated by `scripts/workflows/parity.py` from the browser app's catalogue (`workflows.js`, `_v3`, `_v4`, `_v5`; `scripts/workflows/dump.js` → `browser_workflows.json`): **{len(w)} unique workflows** in {len(by)} categories (the README's \"215\" is an older count).\n",
     "## Status, honestly\n",
     f"* **Ported and tested: {n_port}**. *Audio (44):* the *audio-mastering* chains and the tone/effect/pitch/speed/channel workflows of *audio* and *audio-repair-utility*, as audio filter chains (and a clip speed where the browser app changes tempo) applied to an audio clip from the Effects panel (`workflows.rs`, `AddAudioChain`; `tests/audioworkflows.rs`; GUI `workflows.sh`), built exactly as the browser app's `buildAudioFilterChain()` builds them (`scripts/workflows/build_audio.py`). *Video (42):* the colour-grading, retro, stylize and glitch looks whose settings only use sections 5/7/8/9/13/16/19/31 (plus the two flips), as video filter chains on a video clip (`AddVideoChain`; `tests/videoworkflows.rs`; GUI `videowf.sh`), built as `buildVideoFilterChain()` builds them (`scripts/workflows/build_video.py`). Whether they look/sound the same as in the browser app was not compared by eye or ear.",
     f"* **Not ported: {len(w)-n_port}**. Of those, {sum(1 for x in w if x['id'] in export_ops)} are export/format operations rather than clip workflows and {sum(1 for x in w if x['id'] in native and x['id'] not in ported)} are done natively by existing FFWORKS controls (both noted below). For the rest, FFWORKS has many of the *capabilities* (effects, LUTs, speed/reverse/freeze, transitions, export presets, pixel sort, the mosh/frame/corruption labs) but they are not packaged as one-click workflows and nobody has checked workflow by workflow. Most of the catalogue is settings of the browser app's control panel; what each does lives in `app.js`, so a faithful port means reading that mapping per category (audio is done).\n",
     "## By category\n", "| Category | Workflows | Ported | Data in the catalogue |", "|---|---|---|---|"]
for c, l in by.items():
    kinds = collections.Counter(kind(x) for x in l)
    L.append(f"| {c} | {len(l)} | {sum(1 for x in l if x['id'] in ported)} | {'; '.join(f'{n} × {k}' for k, n in kinds.items())} |")
L.append("\n## Every workflow\n")
for c, l in by.items():
    L += [f"### {c}\n", "| id | name | data | status |", "|---|---|---|---|"]
    for x in l: L.append(f"| `{x['id']}` | {x['name'].replace('|','/')} | {kind(x)} | {status(x)} |")
    L.append("")
open(os.path.join(root, "docs", "WORKFLOW_PARITY.md"), "w").write("\n".join(L))
print(n_port, "ported of", len(w))
