import { invoke } from "@tauri-apps/api/core";
import { listen, type UnlistenFn } from "@tauri-apps/api/event";
import type { JobLog, Command, ClipProps, EffectDef, ProxyStatus, FontEntry, FilterInfo, FilterHelp, FilterGraph, DemoBatch, EngineInfo, FoundEngine, Favourites, RandomResult, ExportPreset, JobEvent, PreviewInfo, RecoveryInfo, AppSettings, BeatAnalysis, Loudness, SceneAnalysis, DetectKind, EffectPreset, RelinkResult, StateView, Waveform } from "./types";

/** Every backend call goes through here so the UI never touches the filesystem or processes directly. */
export const api = {
  getState: () => invoke<StateView>("get_state"),
  newProject: (name: string) => invoke<StateView>("new_project", { name }),
  openProject: (path: string) => invoke<StateView>("open_project", { path }),
  saveProject: (path?: string) => invoke<StateView>("save_project", { path: path ?? null }),
  importMedia: (paths: string[]) => invoke<{ state: StateView; errors: string[] }>("import_media", { paths }),
  dispatch: (command: Command) => invoke<StateView>("dispatch", { command }),
  undo: () => invoke<StateView>("undo"),
  redo: () => invoke<StateView>("redo"),
  getWaveform: (mediaId: string) => invoke<Waveform>("get_waveform", { mediaId }),
  getThumbnails: (mediaId: string) => invoke<string[]>("get_thumbnails", { mediaId }),
  findRecovery: () => invoke<RecoveryInfo | null>("find_recovery"),
  recoverProject: () => invoke<StateView>("recover_project"),
  discardRecovery: () => invoke<void>("discard_recovery"),
  detectScenes: (mediaId: string, threshold: number) => invoke<SceneAnalysis>("detect_scenes", { mediaId, threshold }),
  detectRanges: (mediaId: string, kind: DetectKind, threshold: number, minLen: number) => invoke<[number, number][]>("detect_ranges", { mediaId, kind, threshold, minLen }),
  importImageSequence: (path: string, fps: number) => invoke<{ state: StateView }>("import_image_sequence", { path, fps }),
  packageProject: (folder: string) => invoke<string>("package_project", { folder }),
  startRecording: () => invoke<void>("start_recording"),
  stopRecording: (path: string | null) => invoke<number>("stop_recording", { path }),
  runMacro: (path: string, selected: string | null) => invoke<StateView>("run_macro", { path, selected }),
  importSubtitles: (path: string, offset: number) => invoke<StateView>("import_subtitles", { path, offset }),
  syncOffset: (reference: string, clip: string) => invoke<{ lag: number; confidence: number; start: number }>("sync_offset", { reference, clip }),
  getEffectPresets: () => invoke<Record<string, EffectPreset>>("get_effect_presets"),
  saveEffectPreset: (name: string, preset: EffectPreset) => invoke<Record<string, EffectPreset>>("save_effect_preset", { name, preset }),
  deleteEffectPreset: (name: string) => invoke<Record<string, EffectPreset>>("delete_effect_preset", { name }),
  renderScope: (mediaId: string, time: number, scope: "waveform" | "vectorscope" | "histogram" | "spectrogram") => invoke<string>("render_scope", { mediaId, time, scope }),
  measureLoudness: (mediaId: string) => invoke<Loudness>("measure_loudness", { mediaId }),
  getBeats: (mediaId: string) => invoke<BeatAnalysis>("get_beats", { mediaId }),
  getSettings: () => invoke<AppSettings>("get_settings"),
  setSettings: (ffmpegPath: string | null, ffprobePath: string | null) => invoke<{ ffmpeg: string; ffprobe: string }>("set_settings", { ffmpegPath, ffprobePath }),
  relinkSearch: (dir: string) => invoke<RelinkResult>("relink_search", { dir }),
  relinkMedia: (mediaId: string, path: string) => invoke<StateView>("relink_media", { mediaId, path }),
  getFavourites: () => invoke<Favourites>("get_favourites"),
  setFavourites: (favourites: Favourites) => invoke<Favourites>("set_favourites", { favourites }),
  contactSheet: (clip: string, count: number, stack: number, pool: string, seed: number | null, at: number) => invoke<{ path: string; columns: number; rows: number; seeds: number[]; effects: string[][]; baseSeed: number }>("contact_sheet", { clip, count, stack, pool, seed, at }),
  randomEffects: (clip: string, count: number, pool: string, seed?: number) => invoke<RandomResult>("random_effects", { clip, count, pool, seed: seed ?? null }),
  randomTransitions: (clip: string, count: number, pool: string, seed?: number) => invoke<RandomResult>("random_transitions", { clip, count, pool, seed: seed ?? null, duration: null }),
  listTransitions: () => invoke<[string, string][]>("list_transitions"),
  listEffects: () => invoke<EffectDef[]>("list_effects"),
  proxyStatus: () => invoke<ProxyStatus[]>("proxy_status"),
  createProxy: (mediaId: string) => invoke<string>("create_proxy", { mediaId }),
  clearProxies: () => invoke<number>("clear_proxies"),
  listFonts: () => invoke<FontEntry[]>("list_fonts"),
  listFilters: () => invoke<FilterInfo[]>("list_filters"),
  checkFilterGraph: (graph: FilterGraph) => invoke<string[]>("check_filter_graph", { graph }),
  filterHelp: (name: string) => invoke<FilterHelp>("filter_help", { name }),
  listClipProps: () => invoke<ClipProps>("list_clip_props"),
  renderPreview: (start: string, end: string, scaleDiv: number) => invoke<PreviewInfo>("render_preview", { start, end, scaleDiv }),
  listExportPresets: () => invoke<ExportPreset[]>("list_export_presets"),
  previewCommand: (preset: string, output: string, engine?: string) => invoke<string>("preview_command", { preset, output, engine: engine ?? null }),
  startExport: (preset: string, output: string, engine?: string, keepExisting?: boolean) => invoke<string>("start_export", { preset, output, engine: engine ?? null, keepExisting: keepExisting ?? false }),
  exportName: (template: string, preset: string, date: string, time: string) => invoke<string>("export_name", { template, preset, date, time }),
  demoBatch: (req: { useTransitions: boolean; useEffects: boolean; transitionPool: string; effectPool: string; effectStack: number; includeGl: boolean; segments: number; segmentSecs: number; scaleDiv: number }) => invoke<DemoBatch>("demo_batch", { req }),
  frei0rStatus: () => invoke<{ ffmpegHasFilter: boolean; dirs: string[]; installed: number; offered: string[]; ladspa: { ffmpegHasFilter: boolean; installed: number; offered: number } }>("frei0r_status"),
  setFrei0rDirs: (dirs: string[]) => invoke<void>("set_frei0r_dirs", { dirs }),
  listEngines: () => invoke<{ engines: EngineInfo[]; active: string }>("list_engines"),
  scanEngines: (dir: string) => invoke<FoundEngine[]>("scan_engines", { dir }),
  addEngine: (name: string, ffmpegPath: string, ffprobePath?: string) => invoke<EngineInfo>("add_engine", { name, ffmpegPath, ffprobePath: ffprobePath ?? null }),
  removeEngine: (id: string) => invoke<void>("remove_engine", { id }),
  setActiveEngine: (id: string | null) => invoke<string>("set_active_engine", { id }),
  listJobs: () => invoke<JobEvent[]>("list_jobs"),
  getJobLog: (jobId: string) => invoke<JobLog | null>("get_job_log", { jobId }),
  clearFinishedJobs: () => invoke<void>("clear_finished_jobs"),
  cancelJob: (jobId: string) => invoke<boolean>("cancel_job", { jobId }),
  verifyOutput: (path: string) => invoke<string>("verify_output", { path }),
  diagnostics: () => invoke<Record<string, unknown>>("get_diagnostics"),
  onJob: (cb: (e: JobEvent) => void): Promise<UnlistenFn> => listen<JobEvent>("job-state", (ev) => cb(ev.payload)),
};
